// Eser Listesi verisi - Excel'den içe aktarıldı
// gradePieces: her grade için eser isimleri
const GRADE_PIECES = {
"1": [
  "Anonim – Spanish Dance",
  "Anonim – Sleigh Bells",
  "Halen, O. – Vals",
  "Carcassi, M. – Siciliano",
  "Cano, A. – Divertissement",
  "Ezgi, M. S. – Hatırla Sevgili",
  "Giuliani, M. – Ecossaise, Op. 33 No. 10",
  "Günenç, B. C. – Küçük Etüt No. 04",
  "Schmidt, S. – Kehraus",
  "Carcassi, M. – Prelude",
  "Shearer, A. – Prelude",
  "Carulli, F. – Valse, Op. 241 No. 1",
  "Pinhani – Beni Al",
  "Carulli, F. – La Sautillante",
  "Skinner, T. – Scared of Dark",
  "Ozanoğlu, İ. – Çanakkale İçinde",
  "Carulli, F. – Arpèges de six notes, Op. 241",
  "Anonim – Fransız Halk Şarkısı",
  "Suzuki, S. – Allegro",
  "Carulli, F. – Walze, Op. 241 No. 11",
  "Günenç, B. C. – Küçük Etüt No. 03",
  "Anonim – Grand Waltz",
  "Anonim – Çökertme",
  "Anonim – Spanish Romance",
  "Carulli, F. – Prelude in C",
  "Zimmer, H. – Pirates of the Caribbean",
  "Anonim – Greensleeves",
  "Diabelli, A. – Allegretto, Op. 39 No. 4",
  "Sor, F. – Op. 31 No. 1"
],
"2": [
  "Giuliani, M. – Op. 50 No. 11",
  "Anonim – Kâtibim",
  "Giuliani, M. – Op. 50 No. 1",
  "Calatayud, E. – Vals",
  "Carulli, F. – Rondeau, Op. 247 No. 7",
  "Giuliani, M. – Op. 50 No. 13",
  "Carulli, F. – Op. 241 No. 5",
  "Anonim – Hekimoğlu",
  "Beethoven, L. van – Für Elise",
  "Anonim – Yemen Türküsü",
  "Günenç, B. C. – Küçük Etüt No. 05",
  "Carcassi, M. – Prelude",
  "Carulli, F. – Op. 241 No. 18",
  "Led Zeppelin – Babe I'm Gonna Leave You",
  "Giuliani, M. – Op. 50 No. 3",
  "Fenerbahçe – 100. Yıl Marşı",
  "Anonim – Fikrimin İnce Gülü",
  "Odell, T. – Another Love",
  "Ponce, M. M. – Preludio",
  "Moustaki, G. – Nathalie",
  "Wanders, J. – Rumba",
  "Sor, F. – Andante, Op. 35 No. 1"
],
"3": [
  "Williams, J. – Hedwig's Theme",
  "Günenç, B. C. – Küçük Etüt No. 10",
  "Metallica – Nothing Else Matters",
  "Giuliani, M. – Op. 139 No. 4",
  "Giuliani, M. – Op. 50 No. 2",
  "Carcassi, M. – Allegretto, Op. 21 No. 9",
  "Ferrer, J. – Ejercicio No. 9",
  "Anonim – Wilson's Wilde",
  "Lindsey-Clark, V. – Montañas Nebulosas",
  "Marsh, S. – Cochise",
  "Sánchez, C. – Andalucian Sunrise",
  "Anonim – Golden Dreams",
  "Wanders, J. – Campomoro",
  "Anonim – Tarantella Napoletana",
  "Rota, N. – Speak Softly Love"
],
"4": [
  "Tárrega, F. – Etude in E Minor",
  "Carulli, F. – Allegretto, Op. 241 No. 14",
  "Giuliani, M. – Op. 50 No. 7",
  "Vivaldi, A. – Concerto in D Major RV 93 II: Largo",
  "Sor, F. – Op. 35 No. 22 (Segovia Study No. 5)",
  "Bach, J. S. – Minuet in G Major, BWV Anh. 114",
  "Carulli, F. – Rondo, Op. 241 No. 34",
  "Giuliani, M. – Op. 100 No. 13",
  "Brouwer, L. – Estudio Sencillo No. VI",
  "Anonim – Historia de un Amor"
],
"5": [
  "Anonim (19th C) – Romance",
  "Tárrega, F. – Lágrima",
  "Stachak, T. – Carmen (Tango Waltz)",
  "Brouwer, L. – Estudio No. 6",
  "Giuliani, M. – Allegro Op. 40 No. 6",
  "Sor, F. – Op. 6 No. 11",
  "Carcassi, M. – Andantino Op. 60 No. 3",
  "Anonim – Grosienne No. 1",
  "Lauro, A. – Vals Venezolano No. 2",
  "Handel, G. F. – Passacaglia",
  "Lauro, A. – La Gatica"
],
"6": [
  "Bach, J. S. – Bourrée from BWV 996",
  "Tárrega, F. – Adelita",
  "Giuliani, M. – Allegro Op. 40 No. 6",
  "Giuliani, M. – Maestoso Op. 48 No. 13",
  "Carcassi, M. – Allegro Op. 60 No. 23",
  "Pujol, M. D. – Preludio Tristón",
  "Lauro, A. – El Marabino",
  "Brouwer, L. – Un día de noviembre",
  "Dowland, J. – Preludium",
  "Giuliani, M. – Op. 100 No. 13",
  "Villa-Lobos, H. – Etude No. 1",
  "Tárrega, F. – Rosita"
],
"7": [
  "Villa-Lobos, H. – Prélude No. 3",
  "Llobet, M. – El testament d’Amèlia (arr.)",
  "Lauro, A. – Vals Venezolano No. 1",
  "Bach, J. S. – Allemande from BWV 996",
  "Sor, F. – Cantabile Op. 43 No. 3",
  "Carcassi, M. – Allegro Brillante Op. 60 No. 25",
  "Tárrega, F. – Gran Vals",
  "Pujol, M. D. – Candombe en Mi",
  "Dyens, R. – Mambo des Nuances",
  "Brouwer, L. – Berceuse",
  "Lauro, A. – Carora",
  "Giuliani, M. – Variations on a Theme by Handel Op. 107",
  "Giuliani, M. – Six Variations on Folies d’Espagne Op. 45",
  "Satie, E. – Gnossienne No. 1 (arr. Dyens)"
],
"8": [
  "Bach, J. S. – Gavotte en Rondeau from BWV 1006",
  "Carulli, F. – Overture Op. 6 No. 1",
  "Giuliani, M. – Andantino Op. 111 No. 5",
  "Tárrega, F. – Capricho Árabe",
  "Villa-Lobos, H. – Valsa-Choro",
  "Ponce, M. M. – Campo (from Sonatina Meridional)",
  "Barrios, A. – Preludio Saudade (from La Catedral)",
  "Lauro, A. – Natalia (Valse Criollo)",
  "Sor, F. – Introduction and Variations on a Theme by Mozart",
  "Bach, J. S. – Prelude",
  "Brouwer, L. – La Arpa del Guerrero (from El Decamerón Negro)"
],
};

// studentProgress: ogrenci_id -> { grade: { completed: [bool...], pct } }
// pct artik dinamik hesaplanacak, sadece initial seed olarak kullanilir
const INITIAL_PROGRESS = {
  "s69": {
    "1": {
      "completed": [
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true
      ],
      "pct": 1.0
    },
    "2": {
      "completed": [
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        false,
        true,
        false,
        true
      ],
      "pct": 0.9090909090909091
    },
    "3": {
      "completed": [
        true,
        true,
        false,
        true,
        true,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true
      ],
      "pct": 0.46153846153846156
    },
    "4": {
      "completed": [
        true,
        false,
        true,
        false,
        true,
        true,
        false,
        false,
        false,
        false
      ],
      "pct": 0.4
    },
    "5": {
      "completed": [
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false
      ],
      "pct": 0.09090909090909091
    },
    "6": {
      "completed": [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false
      ],
      "pct": 0.08333333333333333
    }
  },
  "s57": {
    "1": {
      "completed": [
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        false,
        true,
        false,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        false,
        false,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true
      ],
      "pct": 0.8620689655172413
    }
  },
  "s33": {
    "1": {
      "completed": [
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        false,
        true,
        true,
        false,
        false,
        true,
        true,
        true,
        true,
        false,
        false,
        true,
        false,
        false,
        true,
        true,
        true,
        false,
        true,
        true,
        true,
        true
      ],
      "pct": 0.7241379310344828
    },
    "2": {
      "completed": [
        true,
        true,
        true,
        true,
        false,
        true,
        true,
        true,
        false,
        true,
        true,
        true,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false
      ],
      "pct": 0.5454545454545454
    }
  },
  "s63": {
    "1": {
      "completed": [
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        false,
        true,
        true,
        true,
        true,
        true,
        true,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
        true,
        false,
        true,
        true,
        true,
        true,
        true,
        true
      ],
      "pct": 0.7586206896551724
    },
    "2": {
      "completed": [
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false
      ],
      "pct": 0.045454545454545456
    }
  },
  "s61": {
    "1": {
      "completed": [
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        false,
        true,
        true,
        true,
        false,
        false,
        true,
        true,
        false,
        true,
        false,
        false,
        true,
        false,
        true,
        false,
        true,
        true,
        true,
        true,
        true,
        true
      ],
      "pct": 0.7241379310344828
    },
    "2": {
      "completed": [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false
      ],
      "pct": 0.0
    }
  },
  "s37": {
    "1": {
      "completed": [
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        false,
        true,
        true,
        true,
        false,
        true,
        true,
        true,
        false,
        false,
        true,
        false,
        true,
        false,
        true,
        true,
        false,
        false
      ],
      "pct": 0.7241379310344828
    }
  },
  "s30": {
    "1": {
      "completed": [
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        false,
        true,
        false,
        true,
        false,
        true,
        true,
        true,
        true,
        false,
        false,
        true,
        false,
        false,
        true,
        true,
        true,
        false,
        true,
        true,
        true,
        false
      ],
      "pct": 0.6896551724137931
    },
    "2": {
      "completed": [
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false
      ],
      "pct": 0.045454545454545456
    }
  },
  "s06": {
    "1": {
      "completed": [
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        false,
        true,
        false,
        true,
        true,
        true,
        true,
        true,
        false,
        false,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        true,
        true,
        true,
        false
      ],
      "pct": 0.6551724137931034
    },
    "2": {
      "completed": [
        false,
        true,
        true,
        true,
        true,
        false,
        true,
        false,
        true,
        true,
        true,
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
        true
      ],
      "pct": 0.5454545454545454
    },
    "3": {
      "completed": [
        false,
        false,
        false,
        true,
        false,
        false,
        true,
        false,
        true,
        true,
        true,
        false,
        false,
        false,
        true
      ],
      "pct": 0.4
    },
    "4": {
      "completed": [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false
      ],
      "pct": 0.1
    }
  },
  "s31": {
    "1": {
      "completed": [
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        false,
        true,
        false,
        true,
        false,
        true,
        true,
        true,
        false,
        false,
        true,
        true,
        false,
        false,
        true,
        false,
        true,
        false,
        false,
        true,
        true,
        true
      ],
      "pct": 0.6551724137931034
    },
    "2": {
      "completed": [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false
      ],
      "pct": 0.0
    }
  },
  "s18": {
    "1": {
      "completed": [
        true,
        true,
        true,
        true,
        true,
        true,
        false,
        false,
        false,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        true,
        true,
        true,
        false,
        true,
        false,
        false,
        true
      ],
      "pct": 0.6206896551724138
    },
    "2": {
      "completed": [
        false,
        true,
        false,
        true,
        false,
        false,
        false,
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        true,
        true,
        false,
        false,
        false,
        false,
        false
      ],
      "pct": 0.3181818181818182
    }
  },
  "s64": {
    "1": {
      "completed": [
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        false,
        false,
        true,
        true,
        true,
        false,
        true,
        false,
        false,
        true,
        true,
        true,
        true,
        false,
        true,
        false,
        true,
        false,
        false,
        false,
        true,
        false
      ],
      "pct": 0.6206896551724138
    },
    "2": {
      "completed": [
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false
      ],
      "pct": 0.09090909090909091
    }
  },
  "s62": {
    "1": {
      "completed": [
        true,
        true,
        true,
        true,
        true,
        true,
        false,
        false,
        true,
        false,
        true,
        false,
        true,
        true,
        false,
        false,
        false,
        true,
        true,
        false,
        false,
        true,
        true,
        true,
        false,
        true,
        true,
        true,
        false
      ],
      "pct": 0.6206896551724138
    }
  },
  "s05": {
    "1": {
      "completed": [
        false,
        false,
        false,
        true,
        true,
        true,
        true,
        true,
        true,
        false,
        false,
        true,
        true,
        false,
        false,
        false,
        true,
        true,
        true,
        true,
        true,
        false,
        false,
        false,
        true,
        true,
        true,
        true,
        false
      ],
      "pct": 0.5862068965517241
    },
    "2": {
      "completed": [
        true,
        true,
        false,
        false,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false
      ],
      "pct": 0.2727272727272727
    },
    "4": {
      "completed": [
        true,
        false,
        false,
        false,
        true,
        true,
        false,
        false,
        false,
        false
      ],
      "pct": 0.3
    },
    "5": {
      "completed": [
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false
      ],
      "pct": 0.18181818181818182
    },
    "7": {
      "completed": [
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false
      ],
      "pct": 0.07142857142857142
    }
  },
  "s32": {
    "1": {
      "completed": [
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        false,
        true,
        false,
        true,
        false,
        true,
        true,
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        true,
        false,
        true,
        false,
        false,
        true,
        true,
        false
      ],
      "pct": 0.5862068965517241
    },
    "2": {
      "completed": [
        false,
        false,
        false,
        true,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false
      ],
      "pct": 0.13636363636363635
    }
  },
  "s34": {
    "1": {
      "completed": [
        true,
        true,
        true,
        true,
        true,
        true,
        false,
        false,
        true,
        false,
        true,
        false,
        true,
        true,
        true,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        true,
        true,
        true,
        false
      ],
      "pct": 0.5517241379310345
    },
    "2": {
      "completed": [
        false,
        false,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        true,
        false,
        false,
        false,
        false
      ],
      "pct": 0.22727272727272727
    }
  },
  "s14": {
    "1": {
      "completed": [
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        true,
        true,
        true,
        true
      ],
      "pct": 0.5517241379310345
    },
    "2": {
      "completed": [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false
      ],
      "pct": 0.0
    }
  },
  "s58": {
    "1": {
      "completed": [
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        false,
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        true,
        false,
        false,
        true,
        true,
        false
      ],
      "pct": 0.5172413793103449
    },
    "2": {
      "completed": [
        true,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        true,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false
      ],
      "pct": 0.2727272727272727
    }
  },
  "s_extra_1": {
    "1": {
      "completed": [
        true,
        true,
        true,
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        true,
        true,
        false,
        false,
        true,
        true,
        false
      ],
      "pct": 0.5172413793103449
    }
  },
  "s22": {
    "1": {
      "completed": [
        false,
        false,
        true,
        false,
        true,
        true,
        false,
        true,
        true,
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        true,
        true,
        false,
        true,
        false,
        false,
        true,
        true,
        false
      ],
      "pct": 0.4827586206896552
    },
    "2": {
      "completed": [
        false,
        false,
        false,
        true,
        true,
        false,
        false,
        false,
        true,
        false,
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        true,
        false,
        false
      ],
      "pct": 0.36363636363636365
    },
    "3": {
      "completed": [
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        true,
        true,
        false,
        false,
        false,
        true
      ],
      "pct": 0.26666666666666666
    },
    "4": {
      "completed": [
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false
      ],
      "pct": 0.1
    }
  },
  "s36": {
    "1": {
      "completed": [
        true,
        true,
        true,
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        true,
        true,
        false,
        false,
        true,
        true,
        true,
        false,
        false,
        true,
        false,
        true,
        false,
        false,
        false,
        false,
        false
      ],
      "pct": 0.4827586206896552
    }
  },
  "s59": {
    "1": {
      "completed": [
        true,
        true,
        true,
        true,
        true,
        false,
        false,
        false,
        true,
        true,
        true,
        false,
        false,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        true,
        false,
        false,
        true,
        false,
        false,
        false,
        false
      ],
      "pct": 0.4482758620689655
    },
    "2": {
      "completed": [
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false
      ],
      "pct": 0.09090909090909091
    }
  },
  "s35": {
    "1": {
      "completed": [
        true,
        true,
        true,
        true,
        true,
        true,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        true,
        false,
        false,
        true,
        true,
        true
      ],
      "pct": 0.4482758620689655
    },
    "2": {
      "completed": [
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false
      ],
      "pct": 0.18181818181818182
    }
  },
  "s65": {
    "1": {
      "completed": [
        true,
        true,
        true,
        true,
        true,
        true,
        false,
        false,
        false,
        true,
        true,
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        true,
        false,
        false,
        false
      ],
      "pct": 0.4482758620689655
    }
  },
  "s11": {
    "1": {
      "completed": [
        true,
        true,
        true,
        true,
        true,
        true,
        false,
        false,
        true,
        false,
        true,
        false,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        true,
        true,
        false,
        false,
        false,
        false,
        false
      ],
      "pct": 0.4482758620689655
    }
  },
  "s15": {
    "1": {
      "completed": [
        true,
        true,
        true,
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        true,
        true,
        true,
        false,
        false,
        true,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false
      ],
      "pct": 0.41379310344827586
    }
  },
  "s46": {
    "1": {
      "completed": [
        true,
        true,
        true,
        true,
        true,
        true,
        false,
        false,
        true,
        false,
        true,
        false,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        true,
        false,
        false
      ],
      "pct": 0.41379310344827586
    }
  },
  "s23": {
    "1": {
      "completed": [
        true,
        true,
        true,
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false
      ],
      "pct": 0.3448275862068966
    }
  },
  "s60": {
    "1": {
      "completed": [
        true,
        true,
        true,
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false
      ],
      "pct": 0.3103448275862069
    }
  },
  "s28": {
    "1": {
      "completed": [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        true,
        true,
        true,
        false,
        true,
        false
      ],
      "pct": 0.2413793103448276
    },
    "2": {
      "completed": [
        true,
        true,
        false,
        true,
        false,
        true,
        true,
        false,
        true,
        true,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        true,
        false,
        false
      ],
      "pct": 0.45454545454545453
    }
  },
  "s16": {
    "1": {
      "completed": [
        true,
        true,
        true,
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false
      ],
      "pct": 0.2413793103448276
    }
  },
  "s27": {
    "1": {
      "completed": [
        true,
        true,
        true,
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false
      ],
      "pct": 0.20689655172413793
    }
  },
  "s12": {
    "1": {
      "completed": [
        true,
        true,
        true,
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false
      ],
      "pct": 0.20689655172413793
    }
  },
  "s43": {
    "1": {
      "completed": [
        true,
        true,
        true,
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false
      ],
      "pct": 0.20689655172413793
    }
  },
  "s19": {
    "1": {
      "completed": [
        true,
        false,
        true,
        true,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false
      ],
      "pct": 0.1724137931034483
    }
  },
  "s66": {
    "1": {
      "completed": [
        true,
        true,
        true,
        true,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false
      ],
      "pct": 0.1724137931034483
    }
  },
  "s24": {
    "1": {
      "completed": [
        true,
        true,
        true,
        true,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false
      ],
      "pct": 0.1724137931034483
    }
  },
  "s67": {
    "1": {
      "completed": [
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        true,
        true
      ],
      "pct": 0.13793103448275862
    },
    "2": {
      "completed": [
        true,
        false,
        true,
        true,
        true,
        true,
        true,
        true,
        true,
        false,
        true,
        true,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false
      ],
      "pct": 0.5454545454545454
    }
  },
  "s13": {
    "1": {
      "completed": [
        true,
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false
      ],
      "pct": 0.13793103448275862
    }
  },
  "s48": {
    "1": {
      "completed": [
        false,
        true,
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false
      ],
      "pct": 0.13793103448275862
    }
  },
  "s47": {
    "1": {
      "completed": [
        true,
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false
      ],
      "pct": 0.13793103448275862
    }
  },
  "s10": {
    "1": {
      "completed": [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        true,
        false,
        true,
        false
      ],
      "pct": 0.10344827586206896
    },
    "2": {
      "completed": [
        false,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        true,
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false
      ],
      "pct": 0.3181818181818182
    },
    "3": {
      "completed": [
        false,
        true,
        false,
        true,
        false,
        true,
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false
      ],
      "pct": 0.35714285714285715
    }
  },
  "s55": {
    "1": {
      "completed": [
        true,
        true,
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false
      ],
      "pct": 0.1724137931034483
    }
  },
  "s71": {
    "1": {
      "completed": [
        false,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false
      ],
      "pct": 0.06896551724137931
    },
    "2": {
      "completed": [
        true,
        false,
        true,
        true,
        true,
        true,
        true,
        false,
        true,
        false,
        true,
        true,
        true,
        false,
        true,
        false,
        true,
        false,
        true,
        false,
        false,
        false
      ],
      "pct": 0.5909090909090909
    },
    "3": {
      "completed": [
        false,
        true,
        false,
        true,
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false
      ],
      "pct": 0.35714285714285715
    },
    "4": {
      "completed": [
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false
      ],
      "pct": 0.1
    }
  },
  "s25": {
    "1": {
      "completed": [
        true,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false
      ],
      "pct": 0.06896551724137931
    }
  },
  "s29": {
    "1": {
      "completed": [
        true,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false
      ],
      "pct": 0.06896551724137931
    }
  },
  "s74": {
    "1": {
      "completed": [
        true,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false
      ],
      "pct": 0.06896551724137931
    }
  },
  "s54": {
    "1": {
      "completed": [
        true,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false
      ],
      "pct": 0.06896551724137931
    }
  },
  "s26": {
    "1": {
      "completed": [
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false
      ],
      "pct": 0.034482758620689655
    }
  },
  "s41": {
    "1": {
      "completed": [
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false
      ],
      "pct": 0.034482758620689655
    }
  },
  "s39": {
    "1": {
      "completed": [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false
      ],
      "pct": 0.0
    }
  },
  "s42": {
    "1": {
      "completed": [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false
      ],
      "pct": 0.0
    }
  },
  "s53": {
    "1": {
      "completed": [
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false
      ],
      "pct": 0.034482758620689655
    }
  },
  "s56": {
    "1": {
      "completed": [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false
      ],
      "pct": 0.0
    }
  },
  "s08": {
    "2": {
      "completed": [
        false,
        true,
        true,
        false,
        true,
        false,
        true,
        false,
        false,
        false,
        true,
        true,
        true,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        true
      ],
      "pct": 0.4090909090909091
    },
    "3": {
      "completed": [
        false,
        false,
        false,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false
      ],
      "pct": 0.15384615384615385
    },
    "4": {
      "completed": [
        true,
        false,
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        false
      ],
      "pct": 0.4
    },
    "5": {
      "completed": [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false
      ],
      "pct": 0.09090909090909091
    },
    "6": {
      "completed": [
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false
      ],
      "pct": 0.08333333333333333
    },
    "7": {
      "completed": [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false
      ],
      "pct": 0.07142857142857142
    },
    "8": {
      "completed": [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        true,
        false
      ],
      "pct": 0.18181818181818182
    }
  },
  "s20": {
    "2": {
      "completed": [
        true,
        true,
        false,
        true,
        false,
        false,
        false,
        false,
        true,
        true,
        false,
        true,
        false,
        true,
        false,
        false,
        true,
        false,
        false,
        true,
        false,
        false
      ],
      "pct": 0.4090909090909091
    },
    "3": {
      "completed": [
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        true
      ],
      "pct": 0.35714285714285715
    },
    "4": {
      "completed": [
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false
      ],
      "pct": 0.1
    }
  },
  "s04": {
    "2": {
      "completed": [
        false,
        false,
        false,
        true,
        true,
        true,
        false,
        false,
        true,
        true,
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false
      ],
      "pct": 0.36363636363636365
    },
    "3": {
      "completed": [
        false,
        true,
        false,
        true,
        true,
        true,
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false
      ],
      "pct": 0.42857142857142855
    },
    "4": {
      "completed": [
        true,
        false,
        true,
        false,
        true,
        false,
        false,
        true,
        false,
        false
      ],
      "pct": 0.4
    },
    "5": {
      "completed": [
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        true
      ],
      "pct": 0.2727272727272727
    },
    "6": {
      "completed": [
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false
      ],
      "pct": 0.08333333333333333
    }
  },
  "s21": {
    "2": {
      "completed": [
        true,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        true,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false
      ],
      "pct": 0.22727272727272727
    }
  },
  "s09": {
    "2": {
      "completed": [
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false
      ],
      "pct": 0.18181818181818182
    },
    "3": {
      "completed": [
        false,
        true,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true
      ],
      "pct": 0.23076923076923078
    }
  },
  "s68": {
    "2": {
      "completed": [
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false
      ],
      "pct": 0.09090909090909091
    },
    "3": {
      "completed": [
        false,
        true,
        false,
        true,
        true,
        true,
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false
      ],
      "pct": 0.42857142857142855
    },
    "4": {
      "completed": [
        true,
        false,
        false,
        true,
        true,
        false,
        false,
        false,
        true,
        false
      ],
      "pct": 0.4
    }
  },
  "s07": {
    "2": {
      "completed": [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false
      ],
      "pct": 0.045454545454545456
    },
    "3": {
      "completed": [
        false,
        true,
        true,
        true,
        true,
        false,
        true,
        false,
        false,
        false,
        false,
        true,
        true,
        true,
        true
      ],
      "pct": 0.6923076923076923
    },
    "4": {
      "completed": [
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false
      ],
      "pct": 0.1
    },
    "5": {
      "completed": [
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false
      ],
      "pct": 0.09090909090909091
    }
  },
  "s03": {
    "3": {
      "completed": [
        false,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false
      ],
      "pct": 0.15384615384615385
    },
    "4": {
      "completed": [
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false
      ],
      "pct": 0.2
    },
    "5": {
      "completed": [
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false
      ],
      "pct": 0.18181818181818182
    }
  }
};

const EXTRA_STUDENTS = [
  {
    "id": "s_extra_1",
    "name": "Erdinç DOĞRU",
    "pin": "1234"
  }
];