export const ROSTER = [
  { id: 's01', name: 'Dr. Yunus GEDİK' },
  { id: 's02', name: 'Burak SAVAŞ' },
  { id: 's03', name: 'Mustafa Şahin GÜLYEŞİL' },
  { id: 's04', name: 'Dr. Ümit ÇELEBİ' },
  { id: 's05', name: 'Ertuğrul Emre BALKAN' },
  { id: 's06', name: 'Ahmet SARIAHMET' },
  { id: 's07', name: 'Fatih ÖZDÖŞEMECİ' },
  { id: 's08', name: 'Şevval ÖZBEK' },
  { id: 's09', name: 'Şaban Semih ER' },
  { id: 's10', name: 'Turgut KÖKLÜ' },
  { id: 's11', name: 'Nülüfer KARCAN' },
  { id: 's12', name: 'Zehra DİRİLEN' },
  { id: 's13', name: 'Elif AKKOYUN' },
  { id: 's14', name: 'Berfin ÇAKIR' },
  { id: 's15', name: 'Ece ESKİKÖY' },
  { id: 's16', name: 'Numan ERGÜL' },
  { id: 's18', name: 'Nesrin ERDOĞAN' },
  { id: 's19', name: 'Fatma Filiz ERDOĞAN' },
  { id: 's20', name: 'Yasir URGAN' },
  { id: 's21', name: 'Kaya ÖZBOZDUMAN' },
  { id: 's22', name: 'Berra GÜZELLER' },
  { id: 's23', name: 'Filiz KÜÇ' },
  { id: 's24', name: 'Hatice Berra KAYA' },
  { id: 's25', name: 'Elif DEMİR' },
  { id: 's26', name: 'Oğuz POYRAZ' },
  { id: 's27', name: 'Ersin ERGEZER' },
  { id: 's28', name: 'Kaan Doğukan AYDOĞAN' },
  { id: 's29', name: 'Ayşe ÇORBACI' },
  { id: 's30', name: 'Zeynep YİĞİT' },
  { id: 's31', name: 'Bahar ERSOY' },
  { id: 's32', name: 'Kübra KIZMAZ' },
  { id: 's33', name: 'Yavuz ACAR' },
  { id: 's34', name: 'Sena BEKÇİ' },
  { id: 's35', name: 'Dilan ERDOĞAN' },
  { id: 's36', name: 'Recep ÇANKAYA' },
  { id: 's37', name: 'Nevra ARSLANTÜRK' },
  { id: 's38', name: 'Kadri KAYMAK' },
  { id: 's39', name: 'Melike GEDİK' },
  { id: 's40', name: 'Esmanur KARATAŞ' },
  { id: 's41', name: 'Ceren KAYRAK' },
  { id: 's42', name: 'Melisa ÇANKAYA' },
  { id: 's43', name: 'Yeşim MERCAN' },
  { id: 's44', name: 'Begüm Nur VERİM' },
  { id: 's45', name: 'Merve ÖZDEMİR' },
  { id: 's46', name: 'Yasemin BEKTAŞ' },
  { id: 's47', name: 'Ebrar ŞAHİNER' },
  { id: 's48', name: 'Rıfat Cenk AKSOY' },
  { id: 's49', name: 'Handan ALTUNER' },
  { id: 's50', name: 'Havva HOCAOĞLU' },
  { id: 's52', name: 'Meryem ER' },
  { id: 's53', name: 'Ramazan Özgür İRİDERE' },
  { id: 's54', name: 'Av. Yasemin YILDIZ' },
  { id: 's55', name: 'Sema SERBEST' },
  { id: 's56', name: 'Melike DURMUŞ' },
  { id: 's57', name: 'Tomris Ceylan CÖBEK' },
  { id: 's58', name: 'Didem PULAT' },
  { id: 's59', name: 'Av. Arb. Gülçin SABAHLAR' },
  { id: 's60', name: 'Vahide AKDAĞ' },
  { id: 's61', name: 'Zeynep GEZİCİ' },
  { id: 's62', name: 'Dilek ALTAN' },
  { id: 's63', name: 'İbrahim ÇİN' },
  { id: 's64', name: 'Merve YALAP' },
  { id: 's65', name: 'Çiğdem KILIÇ' },
  { id: 's66', name: 'Derya KORKMAZ' },
  { id: 's67', name: 'Dr. Birsen Altaylı ÖZEMİR' },
  { id: 's68', name: 'Doç. Dr. Cihangir ÖZEMİR' },
  { id: 's69', name: 'Oktay Alp KARAATA' },
  { id: 's70', name: 'Pars ODİN' },
  { id: 's71', name: 'Tunç KURTMAN' },
  { id: 's72', name: 'Timur BİR' },
  { id: 's73', name: 'Bora ÖZTEPE' },
  { id: 's74', name: 'Çınar ÇAĞLARIRMAK' },
  { id: 's75', name: 'Ömer' },
  { id: 's76', name: 'Ali Toprak YETİŞ' },
  { id: 's77', name: 'Eyüp Eren' },
  { id: 's78', name: 'Nursev GARİPDOĞAN' },
  { id: 's85', name: 'Misafir' }
];
